.TH amigadepacker 1 "2005-12-07" Linux "user commands"

.SH NAME
amigadepacker \- Tool for depacking some compressed Amiga formats

.SH SYNTAX
.B amigadepacker
[\fB-c\fR] [\fB-h\fR] [\fB-p\fR] [\fB-v\fR] FILE ...

.SH DESCRIPTION
.I amigadepacker
depacks compressed Amiga formats, which are: PowerPacker, XPK SQSH, MMCMP
and StoneCracker 4.04 (S404).
Amigadepacker will automatically determine the compressed format by content.
Among other things, the tool is useful for playing packed Amiga music formats
with
.B uade
(1).

The tool can also be used to decrypt powerpacker encrypted files. That
operation will only take a few hours.


.SH OPTIONS
.TP
.B \-c
Unpack to stdout.
.TP
.B \-h
Display help
.TP
.B \-p
Pretend to unpack, but do not. Prints names of packed files to stderr. Pretend
mode always returns success if arguments are valid. This is useful for
searching packed files.
.TP
.B \-v
Display version information

.SH EXAMPLES
.nf
Unpack a file:
.ft B
amigadepacker foo

.ft R
Unpack a file from stdin to stdout:
.ft B
cat foo |amigadepacker -c > foo.depacked

.ft R
Find all packed files under /path:
.ft B
find /path/ -type f -print0 |xargs -0 amigadepacker -p

.SH AUTHOR
.B amigadepacker
was written by Heikki Orsila <heikki.orsila@iki.fi>. Decompressor for
SQSH format was written by Bert Jahn <jah@fh-zwickau.de>, PowerPacker
depacker and decrypter by Stuart Caie <kyzer@4u.net>, MMCMP depacker
by Olivier Lapicque <olivierl@jps.net> and StoneCracker (S404) depacker
by Jouni "Spiv" Korhonen.
The amigadepacker
web page is located at http://www.iki.fi/shd/foss/amigadepacker/

.SH "SEE ALSO"
\fIlha\fP(1),
\fIppcrack\fP(1),
\fIunadf\fP(1),
\fIunlzx\fP(1),
\fIxdms\fP(1),
\fIxPK\fP(1)

.br
